version: '3'
services:
  grafana-export-to-pdf:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/usr/src/app/output
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
