services:
  grafana-export-to-pdf:
    build: .
    ports:
      - "${EXPORT_SERVER_PORT:-3001}:${EXPORT_SERVER_PORT:-3001}"
    network_mode: "host"
    volumes:
      - ./output:/usr/src/app/output
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - EXPORT_SERVER_PORT=${EXPORT_SERVER_PORT:-3001}
